directories:
  output: dist
  buildResources: build
appId: com.zendariom.launcher
productName: Zendariom Launcher
copyright: Copyright © 2024 Zendariom
files:
  - filter:
      - src/**/*
      - assets/**/*
      - package.json
win:
  target: nsis
  icon: src/assets/images/icon.ico
  verifyUpdateCodeSignature: false
  artifactName: ${productName}-${version}-win-x64.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Zendariom Launcher
publish:
  provider: generic
  url: https://zendariom-upload.onrender.com/download/
  channel: latest
electronVersion: 27.0.4
